[package]
name = "fetch_trees"
version = "0.7.12"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.53"
borsh = "~0.10.3"
clap = { version = "4.2.2", features = ["derive", "cargo"] }
mpl-bubblegum = "1.0.1-beta.3"
solana-account-decoder = "~1.16.16"
solana-client = "~1.16.16"
solana-sdk = "~1.16.16"
spl-account-compression = { version = "0.2.0", features = ["no-entrypoint"] }
tokio = { version = "1.26.0", features = ["full", "tracing"] }

[lints]
workspace = true
