prometheus: 127.0.0.1:8873
geyser_endpoint: http://127.0.0.1:10000
x_token: null
commitment: finalized
max_concurrency: 5
accounts:
  stream: ACCOUNTS
  stream_maxlen: 100_000_000
  filter:
    owner:
      - "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
      - "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
      - "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
      - "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
      - "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"
      - "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
transactions:
  stream: TRANSACTIONS
  stream_maxlen: 10_000_000
  filter:
    account_include:
      - BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY
redis:
  url: redis://localhost:6379
  pipeline_max_size: 1_000
  pipeline_max_idle_ms: 100_000
