replicaCount: 3
proxy:
  sni:
  wildcard: ""
  resources:
    requests:
      cpu: 1
      memory: 512Mi
    limits:
      cpu: 2
      memory: 1024Mi
resources:
  limits:
   cpu: 4
   memory: 1024Mi
  requests:
   cpu: 2
   memory: 512Mi
ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: rpc-devnet.aws.metaplex.com
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:869291162248:certificate/0cc46ab0-42e8-43fe-83a2-a07af82ee213
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-0420dd68c39742f11,subnet-008205ebfdfc8dd32,subnet-0fee43c81fd8dee0d
  hosts:
    - host: rpc-devnet.aws.metaplex.com
      paths:
        - path: /
          pathType: Prefix
  tls: []


